In [1]:
import matplotlib.pyplot as plt
import torch

In [2]:
x = torch.ones(1)
x.requires_grad = True
x

tensor([1.], requires_grad=True)

In [3]:
x

tensor([1.], requires_grad=True)

In [4]:
x.grad

In [5]:
y = 2*x**2 + 3

In [6]:
y

tensor([5.], grad_fn=<AddBackward0>)

In [7]:
y.backward()

In [8]:
x

tensor([1.], requires_grad=True)

In [9]:
x.grad

tensor([4.])

In [10]:
x.grad.data = torch.zeros(1)

In [11]:
x.grad

tensor([0.])

In [12]:
x = torch.zeros(1)
x.requires_grad = True
x

tensor([0.], requires_grad=True)

In [13]:
x

tensor([0.], requires_grad=True)

In [14]:
x.grad

In [15]:
y = 2*x**2 + 3

In [16]:
y

tensor([3.], grad_fn=<AddBackward0>)

In [17]:
y.backward()

In [18]:
x

tensor([0.], requires_grad=True)

In [19]:
x.grad

tensor([0.])

In [20]:
x.grad.data = torch.zeros(1)